import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Radio, Github, FileJson, Globe } from 'lucide-react';
export default function About() {
    return (_jsxs("div", { className: "max-w-3xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-2xl font-bold text-white mb-1", children: "About" }), _jsx("p", { className: "text-gray-400 text-sm", children: "Project information and tech stack" })] }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6", children: [_jsxs("div", { className: "flex items-center gap-4 mb-4", children: [_jsx("div", { className: "w-14 h-14 rounded-2xl bg-blue-600/20 flex items-center justify-center", children: _jsx(Radio, { size: 28, className: "text-blue-400" }) }), _jsxs("div", { children: [_jsx("h2", { className: "text-xl font-bold text-white", children: "Railway VLESS Panel" }), _jsx("p", { className: "text-gray-400 text-sm", children: "v1.0.0" })] })] }), _jsx("p", { className: "text-gray-300 text-sm leading-relaxed", children: "A modern web interface for managing Xray VLESS+WebSocket configurations on Railway. Create, manage, and export VLESS configurations with ease." })] }), _jsxs("div", { className: "bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6", children: [_jsx("h3", { className: "text-white font-semibold mb-4", children: "Tech Stack" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-4 gap-3", children: [
                                    { label: 'React 18', icon: FileJson },
                                    { label: 'TypeScript 5', icon: FileJson },
                                    { label: 'Vite 6', icon: FileJson },
                                    { label: 'Tailwind CSS 4', icon: FileJson },
                                    { label: 'React Router 6', icon: Globe },
                                    { label: 'Xray Core', icon: Radio },
                                    { label: 'Lucide Icons', icon: FileJson },
                                    { label: 'QRCode.react', icon: FileJson },
                                ].map((tech) => (_jsxs("div", { className: "bg-white/5 rounded-xl p-3 text-center hover:bg-white/10 transition-colors", children: [_jsx(tech.icon, { size: 20, className: "mx-auto mb-1 text-blue-400" }), _jsx("p", { className: "text-gray-300 text-xs font-medium", children: tech.label })] }, tech.label))) })] }), _jsxs("div", { className: "bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6", children: [_jsx("h3", { className: "text-white font-semibold mb-4", children: "Links" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("a", { href: "#", className: "flex items-center gap-3 p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-colors", children: [_jsx(Github, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "text-gray-300 text-sm", children: "GitHub Repository" })] }), _jsxs("a", { href: "#", className: "flex items-center gap-3 p-3 rounded-xl bg-white/5 hover:bg-white/10 transition-colors", children: [_jsx(FileJson, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "text-gray-300 text-sm", children: "API Documentation" })] })] })] })] })] }));
}
